version: "2.1"
services:
  # code-server:
  #   build: .
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ../:/root/repos
  #   restart: unless-stopped

  coder:
    image: ghcr.io/coder/coder:latest
    group_add:
      - 115
    ports:
        - 4000:7080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./resolv.conf:/etc/resolv.conf
    environment:
      CODER_ACCESS_URL: "https://code.hxrsmurf.info"
      CODER_ADDRESS: "0.0.0.0:7080"
    networks:
      - nginx-coder

  nginx:
    image: nginx:alpine
    ports:
      - 869:80
      - 870:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./self-signed.conf:/etc/nginx/snippets/self-signed.conf:ro
      - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
    networks:
      - nginx-coder

networks:
  nginx-coder:
    # driver: bridge