version: "2.1"
services:
  # No longer needed, but keeping for now.
  # code-server:
  #   build: .
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ../:/root/repos
  #   restart: unless-stopped

  coder:
    image: ghcr.io/coder/coder:latest
    dns:
      - 192.168.1.1
    group_add:
      - 115 # getent group docker | cut -d: -f3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./resolv.conf:/etc/resolv.conf
    environment:
      CODER_ACCESS_URL: "https://code.hxrsmurf.info"
      CODER_ADDRESS: "0.0.0.0:3000"

  nginx:
    image: nginx:alpine
    ports:
      - 869:80
      - 870:443
      - 3000:443
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../nginx/self-signed.conf:/etc/nginx/snippets/self-signed.conf:ro
      - ../nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ../nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro