version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 869:80
      - 870:443
    volumes:
      - ./tmp:/tmp
      - ./defualt.conf:/etc/nginx/conf.d/default.conf:ro
      - ./self-signed.conf:/etc/nginx/snippets/self-signed.conf:ro
