version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 869:80
      - 870:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./self-signed.conf:/etc/nginx/snippets/self-signed.conf:ro
      - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
networks:
  nginx-coder:
    # driver: bridge